Linkage origins mod
LtxProgrammer/Changed-Minecraft-Mod pull request #1179
Opened 2024-11-20 11:48 UTC by gengyoubo

Fixes #

## Proposed Changes
  -Rewrote Phantom's behavior and added LatexPhantom (a variant of Phantom)
  -Adding configuration files about origins

2024-11-20 22:29 UTC, LtxProgrammer requested changes
I'm not a fan of the classes that are initialized for a single condition check (`CheckCondition`, `LatexPhantom`). I've attempted to communicate this in the previous PRs but that hasn't been successful. There is also no consistency between function names or line spacings.

This code is also not that efficient, with the creation of the check classes and the static map tracking burn cooldowns.

2024-11-20 22:29 UTC, LtxProgrammer commented on src/main/java/net/ltxprogrammer/changed/latexvariant/origins/LatexPhantom.java
> +    private static final Map<ServerPlayer, Long> playerCooldown = new HashMap<>();
See comment later in file on why this map doesn't need to exist.

2024-11-20 22:29 UTC, LtxProgrammer commented on src/main/java/net/ltxprogrammer/changed/latexvariant/origins/LatexPhantom.java
> +                if (phantomPlayer.nowphantom && serverPlayer.level.canSeeSky(serverPlayer.blockPosition())
There's no point in initializing a class just to check the value of one variable. This should just be a static check function.

2024-11-20 22:29 UTC, LtxProgrammer commented on src/main/java/net/ltxprogrammer/changed/process/ProcessTransfur.java
> +            if ((compatibility.isConditionMet()))
This doesn't actually call the function that checks the condition.

2024-11-20 22:29 UTC, LtxProgrammer commented on src/main/resources/META-INF/mods.toml
> +[[dependencies.changed]]
Why is this now a dependency?

2024-11-20 22:29 UTC, LtxProgrammer commented on src/main/java/net/ltxprogrammer/changed/latexvariant/CheckCondition.java
> +package net.ltxprogrammer.changed.latexvariant;
This should go under the `extensions` package alongside the other written compatibilities.

2024-11-20 22:29 UTC, LtxProgrammer commented on src/main/java/net/ltxprogrammer/changed/latexvariant/CheckCondition.java
> +    public int varianttypenumber = 0;
Unused variable. Also is a hard-coded ordinal instead of an enum.

2024-11-20 22:29 UTC, LtxProgrammer commented on src/main/java/net/ltxprogrammer/changed/latexvariant/CheckCondition.java
> +            boolean nowHuman = IOriginContainer.get(player)
Inconsistent line spacing.

2024-11-20 22:29 UTC, LtxProgrammer commented on src/main/java/net/ltxprogrammer/changed/latexvariant/CheckCondition.java
> +    public int VariantTypeNumber() {
Function name should be consistent with everything else in the repo "variantTypeNumber".

2024-11-20 22:29 UTC, LtxProgrammer commented on src/main/resources/data/origins/powers/latextype.json
Filename should be `latex_type.json`

2024-11-21 11:02 UTC, gengyoubo commented on src/main/java/net/ltxprogrammer/changed/latexvariant/origins/LatexPhantom.java
> +                                serverPlayer.setSecondsOnFire(5);
What do you want me to do?

2024-11-21 11:23 UTC, gengyoubo commented on src/main/resources/META-INF/mods.toml
> +[[dependencies.changed]]
mandatory=false

2024-11-23 03:21 UTC, LtxProgrammer commented
Closing as I have implemented config and fixed the issue related to phantoms suffocating when transfurred.

2024-11-23 03:21 UTC, closed without merging