Update ru_ru.json
LtxProgrammer/Changed-Minecraft-Mod pull request #729
Opened 2024-01-22 11:29 UTC by spacedan228

add changes from master to grab mechanic branch pls

2024-01-22 16:34 UTC, LtxProgrammer requested changes
When I merge master into grab-mechanic with both of your PR's there will be duplicate language entries. You'll need to remove them from this PR.

2024-01-22 16:34 UTC, LtxProgrammer commented on src/main/resources/assets/changed/lang/ru_ru.json
> + "changed.config.color_picker_blue": "Синий: %s",
These will be duplicated when I merge the branches

2024-01-22 16:34 UTC, LtxProgrammer commented on src/main/resources/assets/changed/lang/ru_ru.json
> +  "changed.config.bpi.iris_color.right": "Цвет правой радужки",
And so will these

2024-01-22 21:50 UTC, spacedan228 commented
removed

2024-01-23 05:21 UTC, LtxProgrammer approved these changes

2024-01-23 05:22 UTC, merged