Polish Translation Update 2
LtxProgrammer/Changed-Minecraft-Mod pull request #753
Opened 2024-01-30 23:16 UTC by szpigozzzzz

[pl_pl.json](https://github.com/LtxProgrammer/Changed-Minecraft-Mod/files/14105371/pl_pl.json)
At the moment of making that PR im on the phone,so im dropping the .json file that i downloaded from my fork]

## Proposed Changes

  -added translation for partial dl wolf
  -added translation for the new advancement

2024-01-30 23:18 UTC, szpigozzzzz commented
im sorry if i messed something up

2024-01-30 23:20 UTC, spacedan228 commented
ok, actually writing something in "Proposed Changes" is optional

2024-01-30 23:22 UTC, szpigozzzzz commented
understood,i just got used to do that

2024-01-31 03:26 UTC, LtxProgrammer requested changes

2024-01-31 03:26 UTC, LtxProgrammer commented on src/main/resources/assets/changed/lang/pl_pl.json
> +
Small issue, there doesn't need to be a space here between the lines.

2024-02-02 15:25 UTC, merged