Created Model And Texture For Air Conditioner, Fixed Some Latex Creatures Absorbing Instead Of Replicating.
LtxProgrammer/Changed-Minecraft-Mod pull request #931
Opened 2024-06-07 04:28 UTC by bijimio

Air conditioner block code still needs to be touched up; it crashes upon placing.

2024-06-07 10:43 UTC, LtxProgrammer requested changes

2024-06-08 00:54 UTC, bijimio commented
Change had been made, but now, the game crashes upon loading, due to a fatal render thread error.

2024-06-08 12:00 UTC, LtxProgrammer requested changes

2024-06-09 13:35 UTC, LtxProgrammer approved these changes

2024-06-09 13:36 UTC, merged